version: '3.8'
networks:
  grafana:
  prometheus:
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
  prometheus:
    image: 'prom/prometheus:latest'
    command: "--enable-feature=native-histograms --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - '9090:9090'
    networks:
      - grafana
      - prometheus
  grafana:
    image: grafana/grafana:10.0.1
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - grafana
      - prometheus